apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilientrecursion
  labels:
    app: resilientrecursion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resilientrecursion
  template:
    metadata:
      labels:
        app: resilientrecursion
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: resilientrecursion
        image: docker.io/hosseinchb/resilientrecursion
        env:
          - name: REDIS_ADDR
            value: "redis:6379"
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 2586
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        readinessProbe:
          httpGet:
            path: /health
            port: 2586
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 2586
          initialDelaySeconds: 10
          periodSeconds: 10