apiVersion: v1
kind: Service
metadata:
  name: sequence-calc
  labels:
    app: sequence-calc
spec:
  type: LoadBalancer  
  ports:
  - port: 2586
    targetPort: 2586
    protocol: TCP
    name: http
  selector:
    app: resilientrecursion
  sessionAffinity: None
